#!/bin/bash
# Quick Backend Commands

echo "EasyMoney Backend Quick Commands"
echo "================================"
echo ""
echo "1️⃣  START BACKEND"
echo "   /Users/Shubham.Dhamija/AndroidStudioProjects/EasyMoney/start-backend.sh"
echo ""
echo "2️⃣  TEST BACKEND"
echo "   curl http://localhost:8080/"
echo "   curl http://localhost:8080/ai/portfolio?risk=medium"
echo ""
echo "3️⃣  CHECK IF SERVER IS RUNNING"
echo "   ps aux | grep 'node index.js'"
echo ""
echo "4️⃣  STOP SERVER"
echo "   pkill -f 'node index.js'"
echo ""
echo "5️⃣  RESTART SERVER"
echo "   pkill -f 'node index.js'; sleep 2; /Users/Shubham.Dhamija/AndroidStudioProjects/EasyMoney/start-backend.sh"
echo ""
echo "6️⃣  VIEW SERVER LOGS (if running in background)"
echo "   tail -f /tmp/server.log"
echo ""
echo "7️⃣  GET YOUR MAC IP (for physical devices)"
echo "   ifconfig | grep 'inet ' | grep -v 127.0.0.1"
echo ""
echo "8️⃣  KILL PROCESS ON PORT 8080"
echo "   lsof -ti:8080 | xargs kill -9"
echo ""
echo "================================"
echo "Backend URL (Emulator): http://10.0.2.2:8080/"
echo "Backend URL (Device):   http://YOUR_MAC_IP:8080/"
echo "================================"

